print("Please enter your answer under every question")
print("How old are you?")
age = input()
print("How tall are you?")
height = input()
print("How much do you weight?")
weight = input()
print("So, you're {} old, {} tall and {} heavy.".format(age, height, weight))